### ISSUE TITLE
"Could not find kernel image: auto"

### ISSUE THREAD

**Issue by AdrianKielbowicz** [petrkle/debian#1]
After hitting ESC on the boot menu and typing exactly what you have I get:

"Could not find kernel image: auto"

Any ideas?

**Comment by petrkle** [comment]
Sorry, I cant reproduce this error.

Try re-download [debian iso](http://cdimage.debian.org/debian-cd/8.2.0/i386/iso-cd/debian-8.2.0-i386-netinst.iso) and double check boot parameters **auto url=http://petr.kle.cz/debian/jessie**

**Comment by AdrianKielbowicz** [comment]
I was using the LiveCD version of Wheezy i.e. debian-live-7.6.0-i386-standard.iso and not the Network one (debian-7.6.0-i386-netinst.iso) hence why it didn't work..

cheers for your input!

Will come back with more questions later.

Adrian
